# Generated by Django 3.2 on 2021-05-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='image_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
